---
# Keepalived (LB) settings â€” override per environment as needed. Store sensitive values in Vault.
keepalived_interface: eth0
keepalived_virtual_router_id: 51
keepalived_priority_master: 150
keepalived_priority_backup: 100
keepalived_auth_pass: changeme_keepalived_pass
keepalived_virtual_ipaddress:
  - 10.0.0.30
node_role_label: "role=lb"
