---
- name: Initialize Docker Swarm
  hosts: managers[0]
  roles:
    - swarm

- name: Join managers to swarm
  hosts: managers[1:]
  roles:
    - swarm

- name: Join workers to swarm
  hosts: workers
  roles:
    - swarm
  tasks:
    - name: Wait 10s
      pause:
        seconds: 10
